version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend-network
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5012:8080"
      - "7259:8081"
    depends_on:
      - mongodb
    networks:
      - backend-network
    environment:
      - MongoDb__ConnectionURI=mongodb://mongodb:27017
      - MongoDb__DatabaseName=backend

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb_data: